# Generated by Django 2.0.13 on 2019-04-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(unique=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True, unique=True)),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('status', models.TextField()),
                ('senha', models.CharField(max_length=50, null=True)),
                ('curso', models.ManyToManyField(to='laboratorio.Curso')),
                ('funcao', models.ManyToManyField(to='laboratorio.Funcao')),
            ],
        ),
    ]
