# Generated by Django 2.0.13 on 2019-04-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coautor', models.TextField()),
                ('Orientador', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='senha',
            new_name='password',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.StatusArtigo'),
        ),
    ]
