# Generated by Django 2.0.13 on 2019-04-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_auto_20190430_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='curso',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Curso'),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='funcao',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='funcao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Funcao'),
        ),
    ]
