# Generated by Django 2.0.13 on 2019-04-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_auto_20190430_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('titulo', models.TextField()),
                ('corpo', models.TextField()),
                ('data_lancamento_noticia', models.DateTimeField(null=True)),
                ('imagem', models.ImageField(upload_to='noticias')),
                ('autor', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Pessoa')),
            ],
        ),
        migrations.AlterField(
            model_name='artigo',
            name='status',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.StatusArtigo'),
        ),
    ]
