# Generated by Django 2.0.13 on 2019-05-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_auto_20190430_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.StatusArtigo'),
        ),
    ]
