# Generated by Django 2.0.13 on 2019-05-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_auto_20190430_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='Orientador',
        ),
        migrations.AddField(
            model_name='artigo',
            name='orientador',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='coautor',
            field=models.TextField(default=''),
        ),
    ]
