# Generated by Django 2.0.13 on 2019-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_auto_20190501_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField(default='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('qualis', models.TextField(default='')),
                ('area', models.TextField(default='')),
            ],
        ),
    ]
