# Generated by Django 2.0.13 on 2019-05-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default=''),
        ),
    ]
