# Generated by Django 2.0.13 on 2019-05-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_auto_20190501_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Area'),
        ),
    ]
