# Generated by Django 2.0.13 on 2019-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_auto_20190501_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='area',
            field=models.TextField(default=''),
        ),
    ]
