# Generated by Django 2.2.1 on 2019-05-02 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0010_auto_20190501_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Pessoa'),
        ),
    ]
