# Generated by Django 2.2.1 on 2019-05-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_auto_20190502_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', unique=True)),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField(unique=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True, unique=True)),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('status', models.TextField()),
                ('curso', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Curso')),
                ('funcao', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Funcao')),
            ],
        ),
    ]
