# Generated by Django 2.2.1 on 2019-05-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='status',
        ),
    ]
