# Generated by Django 2.2.1 on 2019-05-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_remove_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='funcao',
        ),
    ]
