# Generated by Django 2.2.1 on 2019-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_remove_usuario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.TextField(default=''),
        ),
    ]
