# Generated by Django 2.2.1 on 2019-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0015_auto_20190504_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', unique=True)),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField(unique=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True, unique=True)),
                ('curso', models.TextField(default='')),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('funcao', models.TextField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Aluno',
        ),
    ]
