# Generated by Django 2.2.1 on 2019-05-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0017_auto_20190505_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
    ]
