# Generated by Django 2.2.1 on 2019-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0018_remove_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.TextField(default=''),
        ),
    ]
