# Generated by Django 2.2.1 on 2019-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0019_auto_20190505_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
