# Generated by Django 2.2.1 on 2019-05-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0020_auto_20190505_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
    ]
