# Generated by Django 2.2.1 on 2019-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0021_auto_20190505_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.TextField(default=''),
        ),
    ]
