# Generated by Django 2.2.1 on 2019-05-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0022_auto_20190505_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
    ]
